import 'icon.dart';

// GENERATED by tool/gen_icons.dart from tool/icons/. Do not edit by hand.

/// The names of the built-in icons, for [SheenIcon]:
///
/// ```dart
/// const SheenIcon(SheenIcons.search)
/// const SheenIcon(SheenIcons.heartFill, color: Color(0xFFE5484D))
/// ```
///
/// Stroke icons take a stroke width; `*Fill` names are solid glyphs for tab bars and badges.
///
/// {@category Foundation}
abstract final class SheenIcons {
  /// The arrow up icon.
  static const String arrowUp = 'arrow-up';

  /// The back icon.
  static const String back = 'back';

  /// The bed icon.
  static const String bed = 'bed';

  /// The bell icon.
  static const String bell = 'bell';

  /// The calendar plus icon.
  static const String calendarPlus = 'calendar-plus';

  /// The calendar icon.
  static const String calendar = 'calendar';

  /// The car icon.
  static const String car = 'car';

  /// The card icon.
  static const String card = 'card';

  /// The chat icon.
  static const String chat = 'chat';

  /// The check icon.
  static const String check = 'check';

  /// The chevron down icon.
  static const String chevronDown = 'chevron-down';

  /// The chevron icon.
  static const String chevron = 'chevron';

  /// The clock icon.
  static const String clock = 'clock';

  /// The close icon.
  static const String close = 'close';

  /// The coin icon.
  static const String coin = 'coin';

  /// The compass icon.
  static const String compass = 'compass';

  /// The compose icon.
  static const String compose = 'compose';

  /// The copy icon.
  static const String copy = 'copy';

  /// The directions icon.
  static const String directions = 'directions';

  /// The document icon.
  static const String document = 'document';

  /// The door icon.
  static const String door = 'door';

  /// The download icon.
  static const String download = 'download';

  /// The dumbbell icon.
  static const String dumbbell = 'dumbbell';

  /// The eye icon.
  static const String eye = 'eye';

  /// The filter icon.
  static const String filter = 'filter';

  /// The flag icon.
  static const String flag = 'flag';

  /// The globe icon.
  static const String globe = 'globe';

  /// The grid icon.
  static const String grid = 'grid';

  /// The heart icon.
  static const String heart = 'heart';

  /// The help icon.
  static const String help = 'help';

  /// The hourglass icon.
  static const String hourglass = 'hourglass';

  /// The id card icon.
  static const String idCard = 'id-card';

  /// The image icon.
  static const String image = 'image';

  /// The info icon.
  static const String info = 'info';

  /// The key icon.
  static const String key = 'key';

  /// The layers icon.
  static const String layers = 'layers';

  /// The link icon.
  static const String link = 'link';

  /// The location icon.
  static const String location = 'location';

  /// The lock icon.
  static const String lock = 'lock';

  /// The mail icon.
  static const String mail = 'mail';

  /// The map icon.
  static const String map = 'map';

  /// The mic icon.
  static const String mic = 'mic';

  /// The minus icon.
  static const String minus = 'minus';

  /// The more icon.
  static const String more = 'more';

  /// The navigate icon.
  static const String navigate = 'navigate';

  /// The passport icon.
  static const String passport = 'passport';

  /// The people icon.
  static const String people = 'people';

  /// The phone icon.
  static const String phone = 'phone';

  /// The pin icon.
  static const String pin = 'pin';

  /// The plane icon.
  static const String plane = 'plane';

  /// The plus icon.
  static const String plus = 'plus';

  /// The pool icon.
  static const String pool = 'pool';

  /// The refresh icon.
  static const String refresh = 'refresh';

  /// The room service icon.
  static const String roomService = 'room-service';

  /// The search icon.
  static const String search = 'search';

  /// The share icon.
  static const String share = 'share';

  /// The shield icon.
  static const String shield = 'shield';

  /// The sidebar icon.
  static const String sidebar = 'sidebar';

  /// The sign out icon.
  static const String signOut = 'sign-out';

  /// The sliders icon.
  static const String sliders = 'sliders';

  /// The spa icon.
  static const String spa = 'spa';

  /// The sparkle icon.
  static const String sparkle = 'sparkle';

  /// The star icon.
  static const String star = 'star';

  /// The suitcase icon.
  static const String suitcase = 'suitcase';

  /// The sun icon.
  static const String sun = 'sun';

  /// The swap icon.
  static const String swap = 'swap';

  /// The tag icon.
  static const String tag = 'tag';

  /// The trash icon.
  static const String trash = 'trash';

  /// The user icon.
  static const String user = 'user';

  /// The wallet icon.
  static const String wallet = 'wallet';

  /// The waves icon.
  static const String waves = 'waves';

  /// The wifi icon.
  static const String wifi = 'wifi';

  /// The wrench icon.
  static const String wrench = 'wrench';

  /// The x circle icon.
  static const String xCircle = 'x-circle';

  /// The filled bed glyph.
  static const String bedFill = 'bed.fill';

  /// The filled check circle glyph.
  static const String checkCircleFill = 'check-circle.fill';

  /// The filled compass glyph.
  static const String compassFill = 'compass.fill';

  /// The filled heart glyph.
  static const String heartFill = 'heart.fill';

  /// The filled home glyph.
  static const String homeFill = 'home.fill';

  /// The filled map glyph.
  static const String mapFill = 'map.fill';

  /// The filled star glyph.
  static const String starFill = 'star.fill';

  /// The filled user glyph.
  static const String userFill = 'user.fill';

  /// Every built-in name: the stroke icons, then the filled glyphs.
  static const List<String> all = [
    arrowUp,
    back,
    bed,
    bell,
    calendarPlus,
    calendar,
    car,
    card,
    chat,
    check,
    chevronDown,
    chevron,
    clock,
    close,
    coin,
    compass,
    compose,
    copy,
    directions,
    document,
    door,
    download,
    dumbbell,
    eye,
    filter,
    flag,
    globe,
    grid,
    heart,
    help,
    hourglass,
    idCard,
    image,
    info,
    key,
    layers,
    link,
    location,
    lock,
    mail,
    map,
    mic,
    minus,
    more,
    navigate,
    passport,
    people,
    phone,
    pin,
    plane,
    plus,
    pool,
    refresh,
    roomService,
    search,
    share,
    shield,
    sidebar,
    signOut,
    sliders,
    spa,
    sparkle,
    star,
    suitcase,
    sun,
    swap,
    tag,
    trash,
    user,
    wallet,
    waves,
    wifi,
    wrench,
    xCircle,
    bedFill,
    checkCircleFill,
    compassFill,
    heartFill,
    homeFill,
    mapFill,
    starFill,
    userFill,
  ];
}
