// GENERATED by tool/gen_icons.dart from tool/icons/. Do not edit by hand.

/// Stroke icons: the inner SVG markup of each glyph on a 24 × 24 grid.
const Map<String, String> sheenStrokeIcons = {
  'arrow-up': r'''<path d="M12 19V5.5"></path><path d="m6 11 6-6 6 6"></path>''',
  'back': r'''<path d="M14.5 5.5 8 12l6.5 6.5"></path>''',
  'bed':
      r'''<path d="M3 18V7"></path><path d="M3 14h18v4"></path><path d="M21 14v-2.5A2.5 2.5 0 0 0 18.5 9H11v5"></path><circle cx="7" cy="11" r="1.6"></circle>''',
  'bell': r'''<path d="M6 16.5V11a6 6 0 0 1 12 0v5.5l1.5 1.5h-15Z"></path><path d="M10 20.5h4"></path>''',
  'calendar-plus':
      r'''<rect x="4" y="5.5" width="16" height="14" rx="1.5"></rect><path d="M4 10h16"></path><path d="M8.5 3.5v4"></path><path d="M15.5 3.5v4"></path><path d="M12 12.5v5"></path><path d="M9.5 15h5"></path>''',
  'calendar':
      r'''<rect x="4" y="5.5" width="16" height="14" rx="1.5"></rect><path d="M4 10h16"></path><path d="M8.5 3.5v4"></path><path d="M15.5 3.5v4"></path>''',
  'car':
      r'''<path d="M5 16.5V12l2-5h10l2 5v4.5"></path><path d="M3.5 12h17v4.5h-17Z"></path><circle cx="7.5" cy="14.3" r=".8"></circle><circle cx="16.5" cy="14.3" r=".8"></circle><path d="M6 16.5v2"></path><path d="M18 16.5v2"></path>''',
  'card':
      r'''<rect x="3" y="5.5" width="18" height="13" rx="2"></rect><path d="M3 9.5h18"></path><path d="M6.5 15h4"></path>''',
  'chat': r'''<path d="M4 5.5h16v10H9.5L5 19.5v-4H4Z"></path><path d="M8.5 10.5h7"></path>''',
  'check': r'''<path d="m5 12.5 4.5 4.5L19 7.5"></path>''',
  'chevron-down': r'''<path d="m6 9.5 6 6 6-6"></path>''',
  'chevron': r'''<path d="m9.5 5.5 6.5 6.5-6.5 6.5"></path>''',
  'clock': r'''<circle cx="12" cy="12" r="8.5"></circle><path d="M12 7.5V12l3 2"></path>''',
  'close': r'''<path d="m6.5 6.5 11 11"></path><path d="m17.5 6.5-11 11"></path>''',
  'coin':
      r'''<circle cx="12" cy="12" r="8.5"></circle><path d="M14.5 9.2c-.5-.9-1.4-1.4-2.5-1.4-1.5 0-2.6.8-2.6 2s1.1 1.6 2.6 1.9 2.6.8 2.6 2-1.1 2-2.6 2c-1.1 0-2-.5-2.5-1.4"></path><path d="M12 6.3v1.5"></path><path d="M12 16.2v1.5"></path>''',
  'compass': r'''<circle cx="12" cy="12" r="8.5"></circle><path d="m15.5 8.5-2 5-5 2 2-5Z"></path>''',
  'compose':
      r'''<path d="M12 4.5H6.5a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V12"></path><path d="M17.5 3.5a1.8 1.8 0 0 1 2.5 2.5L12.5 13.5 9 14.5l1-3.5Z"></path>''',
  'copy':
      r'''<rect x="8.5" y="8.5" width="11" height="11" rx="2"></rect><path d="M15.5 8.5v-2a2 2 0 0 0-2-2h-7a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h2"></path>''',
  'directions':
      r'''<path d="M12 2.8 21.2 12 12 21.2 2.8 12Z"></path><path d="M9.5 14.5v-2.5a1.5 1.5 0 0 1 1.5-1.5h3.5"></path><path d="m13 8.5 2 2-2 2"></path>''',
  'document':
      r'''<path d="M6 3.5h8l4 4v13H6Z"></path><path d="M14 3.5v4h4"></path><path d="M9 12.5h6"></path><path d="M9 16h6"></path>''',
  'door':
      r'''<path d="M5 20.5h14"></path><path d="M7 20.5V4.5h10v16"></path><circle cx="14" cy="12.5" r=".9"></circle>''',
  'download':
      r'''<path d="M12 4.5V15"></path><path d="m7.5 10.5 4.5 4.5 4.5-4.5"></path><path d="M5 19.5h14"></path>''',
  'dumbbell':
      r'''<path d="M6.5 8v8"></path><path d="M17.5 8v8"></path><path d="M3.5 10v4"></path><path d="M20.5 10v4"></path><path d="M6.5 12h11"></path>''',
  'eye':
      r'''<path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12Z"></path><circle cx="12" cy="12" r="3"></circle>''',
  'filter': r'''<path d="M4 6.5h16"></path><path d="M7 12h10"></path><path d="M10 17.5h4"></path>''',
  'flag': r'''<path d="M5 20.5v-16"></path><path d="M5 4.5h11l-2 4 2 4H5"></path>''',
  'globe':
      r'''<circle cx="12" cy="12" r="8.5"></circle><path d="M3.5 12h17"></path><path d="M12 3.5c2.4 2.4 3.5 5.2 3.5 8.5s-1.1 6.1-3.5 8.5c-2.4-2.4-3.5-5.2-3.5-8.5s1.1-6.1 3.5-8.5Z"></path>''',
  'grid':
      r'''<rect x="4" y="4" width="7" height="7" rx="1.2"></rect><rect x="13" y="4" width="7" height="7" rx="1.2"></rect><rect x="4" y="13" width="7" height="7" rx="1.2"></rect><rect x="13" y="13" width="7" height="7" rx="1.2"></rect>''',
  'heart':
      r'''<path d="M12 19.5s-7.5-4.4-7.5-10A4.2 4.2 0 0 1 12 7a4.2 4.2 0 0 1 7.5 2.5c0 5.6-7.5 10-7.5 10Z"></path>''',
  'help':
      r'''<circle cx="12" cy="12" r="8.5"></circle><path d="M9.6 9.5a2.5 2.5 0 0 1 4.8.8c0 1.7-2.4 2-2.4 3.6"></path><path d="M12 16.8v.3"></path>''',
  'hourglass':
      r'''<path d="M7 3.5h10"></path><path d="M7 20.5h10"></path><path d="M8 3.5c0 4 4 5 4 8.5 0-3.5 4-4.5 4-8.5"></path><path d="M8 20.5c0-4 4-5 4-8.5 0 3.5 4 4.5 4 8.5"></path>''',
  'id-card':
      r'''<rect x="3" y="5.5" width="18" height="13" rx="2"></rect><circle cx="8.5" cy="11" r="2"></circle><path d="M5.8 15.5c.6-1.4 1.6-2 2.7-2s2.1.6 2.7 2"></path><path d="M14 10h4"></path><path d="M14 13.5h3"></path>''',
  'image':
      r'''<rect x="3.5" y="4.5" width="17" height="15" rx="2.5"></rect><circle cx="9" cy="10" r="1.8"></circle><path d="m4 17.5 5-4.5 4 3.5 2.5-2 4.5 3.5"></path>''',
  'info': r'''<circle cx="12" cy="12" r="8.5"></circle><path d="M12 11v5"></path><path d="M12 7.6v.4"></path>''',
  'key':
      r'''<circle cx="8" cy="12" r="3.5"></circle><path d="M11.5 12H20.5"></path><path d="M17.5 12v3"></path><path d="M20.5 12v2"></path>''',
  'layers':
      r'''<path d="m12 4 8.5 4.5L12 13 3.5 8.5Z"></path><path d="m3.5 12.5 8.5 4.5 8.5-4.5"></path><path d="m3.5 16.5 8.5 4.5 8.5-4.5"></path>''',
  'link':
      r'''<path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"></path><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"></path>''',
  'location': r'''<path d="M20 4 4 11l7 2 2 7Z"></path>''',
  'lock':
      r'''<rect x="5" y="10.5" width="14" height="10" rx="2"></rect><path d="M8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5"></path>''',
  'mail': r'''<rect x="3.5" y="5.5" width="17" height="13" rx="2"></rect><path d="m4 7 8 6 8-6"></path>''',
  'map':
      r'''<path d="M9 4.5 3.5 6.5v13l5.5-2 6 2 5.5-2v-13l-5.5 2-6-2Z"></path><path d="M9 4.5v13"></path><path d="M15 6.5v13"></path>''',
  'mic':
      r'''<rect x="9" y="3.5" width="6" height="11" rx="3"></rect><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0"></path><path d="M12 18v2.5"></path>''',
  'minus': r'''<path d="M5 12h14"></path>''',
  'more':
      r'''<circle cx="6" cy="12" r="1.1"></circle><circle cx="12" cy="12" r="1.1"></circle><circle cx="18" cy="12" r="1.1"></circle>''',
  'navigate': r'''<path d="m4 11.5 16-7-7 16-2-7Z"></path>''',
  'passport':
      r'''<rect x="5.5" y="3.5" width="13" height="17" rx="1.5"></rect><circle cx="12" cy="11" r="3.3"></circle><path d="M8.7 11h6.6"></path><path d="M9 16.5h6"></path>''',
  'people':
      r'''<circle cx="9" cy="9" r="3"></circle><path d="M3.5 18.5c.8-2.8 3-4.3 5.5-4.3s4.7 1.5 5.5 4.3"></path><circle cx="16.5" cy="9.5" r="2.5"></circle><path d="M16 14.3c2.2.1 3.9 1.5 4.5 4.2"></path>''',
  'phone':
      r'''<path d="M6.5 3.5h3l1.5 4.5-2 1.3a10.5 10.5 0 0 0 5.7 5.7l1.3-2 4.5 1.5v3a2 2 0 0 1-2.2 2A16.5 16.5 0 0 1 4.5 5.7a2 2 0 0 1 2-2.2Z"></path>''',
  'pin':
      r'''<path d="M12 21s6.5-6.3 6.5-11A6.5 6.5 0 0 0 5.5 10c0 4.7 6.5 11 6.5 11Z"></path><circle cx="12" cy="10" r="2.3"></circle>''',
  'plane':
      r'''<path d="M10.5 13.5 4 11l1.5-1.5 7 1L17 6c1-1 2.6-1.3 3-.9.4.4.1 2-.9 3l-4.5 4.5 1 7L14 21l-2.5-6.5-3 3V20L7 21l-1-3-3-1 1-1.5h2.5Z"></path>''',
  'plus': r'''<path d="M12 5v14"></path><path d="M5 12h14"></path>''',
  'pool':
      r'''<path d="M3 17c1.5 0 1.5-1.2 3-1.2s1.5 1.2 3 1.2 1.5-1.2 3-1.2 1.5 1.2 3 1.2 1.5-1.2 3-1.2 1.5 1.2 3 1.2"></path><path d="M8 14V6a2 2 0 0 1 4 0"></path><path d="M14 14V6a2 2 0 0 1 4 0"></path><path d="M8 9h6"></path>''',
  'refresh': r'''<path d="M19.5 12a7.5 7.5 0 1 1-2.2-5.3"></path><path d="M19.5 4.5v4h-4"></path>''',
  'room-service':
      r'''<path d="M4 17.5h16"></path><path d="M5.5 17.5a6.5 6.5 0 0 1 13 0"></path><path d="M12 9V7.5"></path><path d="M10.5 7.5h3"></path>''',
  'search': r'''<circle cx="11" cy="11" r="6.5"></circle><path d="M16 16l4.5 4.5"></path>''',
  'share': r'''<path d="M12 15V4.5"></path><path d="m8 8.5 4-4 4 4"></path><path d="M5.5 12.5v6h13v-6"></path>''',
  'shield': r'''<path d="M12 3.5 19 6v5.5c0 4.3-3 7.8-7 9-4-1.2-7-4.7-7-9V6Z"></path><path d="m9 12 2 2 4-4"></path>''',
  'sidebar': r'''<rect x="3.5" y="4.5" width="17" height="15" rx="2.5"></rect><path d="M9.5 4.5v15"></path>''',
  'sign-out':
      r'''<path d="M14 4.5h4.5a1.5 1.5 0 0 1 1.5 1.5v12a1.5 1.5 0 0 1-1.5 1.5H14"></path><path d="M10 16.5 5.5 12 10 7.5"></path><path d="M5.5 12H15"></path>''',
  'sliders':
      r'''<path d="M4 7h10"></path><path d="M18 7h2"></path><circle cx="16" cy="7" r="2"></circle><path d="M4 17h2"></path><path d="M10 17h10"></path><circle cx="8" cy="17" r="2"></circle>''',
  'spa':
      r'''<path d="M12 20c-4.5 0-8-2.8-8.5-7 2.8 0 5.6 1.2 8.5 4.2 2.9-3 5.7-4.2 8.5-4.2-.5 4.2-4 7-8.5 7Z"></path><path d="M12 17.2c-1.8-2.4-2.5-5-1.9-8C10.6 7 11.2 5.4 12 4c.8 1.4 1.4 3 1.9 5.2.6 3-.1 5.6-1.9 8Z"></path>''',
  'sparkle':
      r'''<path d="M12 3.5c.6 3.9 2.6 5.9 6.5 6.5-3.9.6-5.9 2.6-6.5 6.5-.6-3.9-2.6-5.9-6.5-6.5 3.9-.6 5.9-2.6 6.5-6.5Z"></path><path d="M18.5 15.5c.3 1.6 1.1 2.4 2.5 2.7-1.4.3-2.2 1.1-2.5 2.6-.3-1.5-1.1-2.3-2.5-2.6 1.4-.3 2.2-1.1 2.5-2.7Z"></path>''',
  'star': r'''<path d="m12 4 2.4 5 5.4.6-4 3.7 1.1 5.4L12 16l-4.9 2.7 1.1-5.4-4-3.7 5.4-.6Z"></path>''',
  'suitcase':
      r'''<rect x="4" y="7" width="16" height="12" rx="1.5"></rect><path d="M9 7V5h6v2"></path><path d="M4 12h16"></path>''',
  'sun':
      r'''<circle cx="12" cy="12" r="4"></circle><path d="M12 2.5v2"></path><path d="M12 19.5v2"></path><path d="M2.5 12h2"></path><path d="M19.5 12h2"></path><path d="m5.3 5.3 1.4 1.4"></path><path d="m17.3 17.3 1.4 1.4"></path><path d="m5.3 18.7 1.4-1.4"></path><path d="m17.3 6.7 1.4-1.4"></path>''',
  'swap': r'''<path d="M7 7h11l-3-3"></path><path d="M17 17H6l3 3"></path>''',
  'tag':
      r'''<path d="M3.5 12.2V4.5a1 1 0 0 1 1-1h7.7l8.3 8.3a1 1 0 0 1 0 1.4l-7.3 7.3a1 1 0 0 1-1.4 0Z"></path><circle cx="8" cy="8" r="1.4"></circle>''',
  'trash': r'''<path d="M4.5 6.5h15"></path><path d="M9.5 6.5V4.5h5v2"></path><path d="M6.5 6.5l1 13h9l1-13"></path>''',
  'user': r'''<circle cx="12" cy="8.5" r="3.5"></circle><path d="M5 19.5c1.2-3.3 4-5 7-5s5.8 1.7 7 5"></path>''',
  'wallet':
      r'''<rect x="3.5" y="6" width="17" height="13" rx="2.5"></rect><path d="M3.5 10h17"></path><path d="M6 6V5a1.5 1.5 0 0 1 1.5-1.5h9A1.5 1.5 0 0 1 18 5v1"></path>''',
  'waves':
      r'''<path d="M3 9c1.5 0 1.5-1.5 3-1.5S7.5 9 9 9s1.5-1.5 3-1.5S13.5 9 15 9s1.5-1.5 3-1.5S19.5 9 21 9"></path><path d="M3 15c1.5 0 1.5-1.5 3-1.5S7.5 15 9 15s1.5-1.5 3-1.5S13.5 15 15 15s1.5-1.5 3-1.5S19.5 15 21 15"></path>''',
  'wifi':
      r'''<path d="M3 9a13 13 0 0 1 18 0"></path><path d="M6.2 12.5a8.5 8.5 0 0 1 11.6 0"></path><path d="M9.3 15.8a4 4 0 0 1 5.4 0"></path><circle cx="12" cy="19" r=".9"></circle>''',
  'wrench':
      r'''<path d="M14.5 4a5 5 0 0 0-5.6 6.6L3.8 15.7a1.8 1.8 0 0 0 2.5 2.5l5.1-5.1A5 5 0 0 0 18 7.5l-3 3-2.5-.5-.5-2.5 3-3a5 5 0 0 0-.5-.5Z"></path>''',
  'x-circle': r'''<circle cx="12" cy="12" r="8.5"></circle><path d="m9 9 6 6"></path><path d="m15 9-6 6"></path>''',
};

/// Filled glyphs: the inner SVG markup of each glyph on a 24 × 24 grid.
const Map<String, String> sheenFilledIcons = {
  'bed':
      r'''<path d="M2.5 6.5a1 1 0 0 1 2 0V13h7V9.5c0-.6.4-1 1-1h5.5a3.5 3.5 0 0 1 3.5 3.5v7a1 1 0 0 1-2 0v-2h-15v2a1 1 0 0 1-2 0Z"></path><circle cx="7.5" cy="10" r="2"></circle>''',
  'check-circle':
      r'''<path fill-rule="evenodd" d="M12 2.5a9.5 9.5 0 1 1 0 19 9.5 9.5 0 0 1 0-19Zm4.3 6.3a.9.9 0 0 0-1.3 0l-4.3 4.6-1.8-1.8a.9.9 0 1 0-1.3 1.3l2.5 2.4c.4.4 1 .4 1.3 0l5-5.3c.3-.4.3-.9-.1-1.2Z"></path>''',
  'compass':
      r'''<path fill-rule="evenodd" d="M12 2.4a9.6 9.6 0 1 1 0 19.2 9.6 9.6 0 0 1 0-19.2Zm4.1 5.5-5.6 2.6-2.6 5.6 5.6-2.6Z"></path>''',
  'heart':
      r'''<path d="M12 20.3S3.5 15.5 3.5 9.3A4.6 4.6 0 0 1 12 6.8a4.6 4.6 0 0 1 8.5 2.5c0 6.2-8.5 11-8.5 11Z"></path>''',
  'home':
      r'''<path d="M12 3.1 2.8 10.4a.9.9 0 0 0 .6 1.6H5v7.6c0 .8.6 1.4 1.4 1.4h3.8v-5.6h3.6V21h3.8c.8 0 1.4-.6 1.4-1.4V12h1.6a.9.9 0 0 0 .6-1.6Z"></path>''',
  'map':
      r'''<path d="M8.6 3.6 3.9 5.4a1.4 1.4 0 0 0-.9 1.3v12.6c0 .7.7 1.2 1.3.9l4.3-1.6Z"></path><path d="M10.2 3.6v15l4.6 2V5.6Z"></path><path d="M16.4 5.6v15l4.7-1.8c.5-.2.9-.7.9-1.3V4.9c0-.7-.7-1.2-1.3-.9Z"></path>''',
  'star': r'''<path d="m12 3.6 2.5 5.2 5.6.6-4.2 3.8 1.2 5.6L12 16l-5.1 2.8 1.2-5.6L3.9 9.4l5.6-.6Z"></path>''',
  'user':
      r'''<circle cx="12" cy="7.6" r="4.1"></circle><path d="M3.9 20c.7-4 4.1-6.6 8.1-6.6s7.4 2.6 8.1 6.6c.1.6-.4 1.1-1 1.1H4.9c-.6 0-1.1-.5-1-1.1Z"></path>''',
};
