// Generates lib/src/icons/icon_data.dart and lib/src/icons/icons.dart from the SVG files in tool/icons/.
//
// tool/icons/stroke/<name>.svg  stroke icons on a 24 × 24 grid (round caps and joins; the stroke width is applied at
//                               draw time)
// tool/icons/filled/<name>.svg  filled glyphs on a 24 × 24 grid (tab bars, badges), addressed as '<name>.fill'
//
// Run: dart run tool/gen_icons.dart
import 'dart:io';

String inner(File f) {
  final s = f.readAsStringSync().trim();
  final open = s.indexOf('>');
  final close = s.lastIndexOf('</svg>');
  if (!s.startsWith('<svg') || open < 0 || close < 0) throw FormatException('Not an <svg> document', f.path);
  final body = s.substring(open + 1, close).trim();
  if (body.contains("'''") || body.contains('\n')) throw FormatException('Unexpected markup', f.path);
  return body;
}

Map<String, String> read(String dir) {
  final files = Directory(dir).listSync().whereType<File>().where((f) => f.path.endsWith('.svg')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  return {for (final f in files) f.uri.pathSegments.last.replaceAll('.svg', ''): inner(f)};
}

String camel(String name) {
  final parts = name.split('-');
  return parts.first + parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String words(String name) => name.replaceAll('-', ' ');

void main() {
  final stroke = read('tool/icons/stroke');
  final filled = read('tool/icons/filled');

  final data = StringBuffer()
    ..writeln('// GENERATED by tool/gen_icons.dart from tool/icons/. Do not edit by hand.')
    ..writeln()
    ..writeln('/// Stroke icons: the inner SVG markup of each glyph on a 24 × 24 grid.')
    ..writeln('const Map<String, String> sheenStrokeIcons = {');
  stroke.forEach((k, v) => data.writeln("  '$k': r'''$v''',"));
  data
    ..writeln('};')
    ..writeln()
    ..writeln('/// Filled glyphs: the inner SVG markup of each glyph on a 24 × 24 grid.')
    ..writeln('const Map<String, String> sheenFilledIcons = {');
  filled.forEach((k, v) => data.writeln("  '$k': r'''$v''',"));
  data.writeln('};');
  File('lib/src/icons/icon_data.dart').writeAsStringSync(data.toString());

  final names = StringBuffer()
    ..writeln('// GENERATED by tool/gen_icons.dart from tool/icons/. Do not edit by hand.')
    ..writeln()
    ..writeln('/// The names of the built-in icons, for [SheenIcon]:')
    ..writeln('///')
    ..writeln('/// ```dart')
    ..writeln('/// const SheenIcon(SheenIcons.search)')
    ..writeln('/// const SheenIcon(SheenIcons.heartFill, color: Color(0xFFE5484D))')
    ..writeln('/// ```')
    ..writeln('///')
    ..writeln('/// Stroke icons take a stroke width; `*Fill` names are solid glyphs for tab bars and badges.')
    ..writeln('///')
    ..writeln('/// {@category Foundation}')
    ..writeln('abstract final class SheenIcons {');
  for (final k in stroke.keys) {
    names
      ..writeln('  /// The ${words(k)} icon.')
      ..writeln("  static const String ${camel(k)} = '$k';")
      ..writeln();
  }
  for (final k in filled.keys) {
    names
      ..writeln('  /// The filled ${words(k)} glyph.')
      ..writeln("  static const String ${camel(k)}Fill = '$k.fill';")
      ..writeln();
  }
  names
    ..writeln('  /// Every built-in name: the stroke icons, then the filled glyphs.')
    ..writeln('  static const List<String> all = [')
    ..writeln(stroke.keys.map((k) => '    ${camel(k)},').join('\n'))
    ..writeln(filled.keys.map((k) => '    ${camel(k)}Fill,').join('\n'))
    ..writeln('  ];')
    ..writeln('}');
  File('lib/src/icons/icons.dart').writeAsStringSync("import 'icon.dart';\n\n$names");
  stdout.writeln('wrote ${stroke.length} stroke and ${filled.length} filled icons');
}
